// ==============================================================================
// AUTO-GENERATED by copper.protocol.codegen. DO NOT EDIT.
// Source of truth: copper-2/copper/protocol/{apply_plan,events,context}.py
// To regenerate: cd copper-2 && python -m copper.protocol.codegen \
//                     --target cpp --out <kicad-copper>/eeschema/copper/copper_types.generated.h
// ==============================================================================

#ifndef KICAD_COPPER_TYPES_GENERATED_H
#define KICAD_COPPER_TYPES_GENERATED_H

#include <string>
#include <vector>
#include <variant>
#include <optional>
#include <cstdint>

#include <nlohmann/json.hpp>

namespace COPPER { namespace generated {

inline constexpr int PROTOCOL_VERSION = 1;
inline constexpr long long COORD_MIN = -1000000000LL;
inline constexpr long long COORD_MAX = 1000000000LL;

// ── Operation structs ──────────────────────────────────────────────────────

struct PlaceComponentOp {
    std::string lib_id;
    std::string reference;
    std::string value;
    int32_t     x = 0;
    int32_t     y = 0;
    double      rotation = 0.0;

    static PlaceComponentOp from_json( const nlohmann::json& j );
    nlohmann::json          to_json() const;
};

struct AddWireOp {
    int32_t start_x = 0, start_y = 0, end_x = 0, end_y = 0;

    static AddWireOp from_json( const nlohmann::json& j );
    nlohmann::json   to_json() const;
};

struct AddLabelOp {
    std::string name;
    int32_t     x = 0;
    int32_t     y = 0;
    std::string label_type = "local";  // local|global|hierarchical
    double      rotation = 0.0;

    static AddLabelOp from_json( const nlohmann::json& j );
    nlohmann::json    to_json() const;
};

struct AddJunctionOp {
    int32_t x = 0;
    int32_t y = 0;

    static AddJunctionOp from_json( const nlohmann::json& j );
    nlohmann::json       to_json() const;
};

struct AddPowerSymbolOp {
    std::string net_name;
    int32_t     x = 0;
    int32_t     y = 0;
    double      rotation = 0.0;

    static AddPowerSymbolOp from_json( const nlohmann::json& j );
    nlohmann::json          to_json() const;
};

using OperationVariant = std::variant<
    PlaceComponentOp,
    AddWireOp,
    AddLabelOp,
    AddJunctionOp,
    AddPowerSymbolOp
>;

OperationVariant parseOperation( const nlohmann::json& j );

// ── PlanCard, ErcReport ────────────────────────────────────────────────────

struct PlanStep {
    int         index = 0;
    std::string description;
};

struct PlanCard {
    std::vector<PlanStep> steps;
    std::string           placement_info;
};

struct ErcMessage {
    std::string severity;
    std::string code;
    std::string text;
    std::vector<std::string> refs;
};

struct ErcReport {
    int errors = 0;
    int warnings = 0;
    std::vector<ErcMessage> messages;
};

// ── ApplyPlan (the full payload of a `done` event / apply-plan.json) ───────

struct ApplyPlan {
    int                          protocol_version = PROTOCOL_VERSION;
    bool                         success = true;
    std::string                  intent = "generate";
    std::string                  message;
    std::vector<OperationVariant> operations;
    PlanCard                     plan;
    std::optional<ErcReport>     erc;
    std::string                  error;

    static ApplyPlan from_json( const nlohmann::json& j );
};

} }  // namespace COPPER::generated

#endif  // KICAD_COPPER_TYPES_GENERATED_H

namespace COPPER { namespace generated {

inline PlaceComponentOp PlaceComponentOp::from_json( const nlohmann::json& j ) {
    PlaceComponentOp o;
    o.lib_id    = j.value( "lib_id", "" );
    o.reference = j.value( "reference", "" );
    o.value     = j.value( "value", "" );
    o.x         = j.value( "x", 0 );
    o.y         = j.value( "y", 0 );
    o.rotation  = j.value( "rotation", 0.0 );
    return o;
}

inline nlohmann::json PlaceComponentOp::to_json() const {
    return { {"type","PLACE_COMPONENT"}, {"lib_id",lib_id}, {"reference",reference},
             {"value",value}, {"x",x}, {"y",y}, {"rotation",rotation} };
}

inline AddWireOp AddWireOp::from_json( const nlohmann::json& j ) {
    AddWireOp o;
    o.start_x = j.value( "start_x", 0 );
    o.start_y = j.value( "start_y", 0 );
    o.end_x   = j.value( "end_x", 0 );
    o.end_y   = j.value( "end_y", 0 );
    return o;
}

inline nlohmann::json AddWireOp::to_json() const {
    return { {"type","ADD_WIRE"}, {"start_x",start_x}, {"start_y",start_y},
             {"end_x",end_x}, {"end_y",end_y} };
}

inline AddLabelOp AddLabelOp::from_json( const nlohmann::json& j ) {
    AddLabelOp o;
    o.name       = j.value( "name", "" );
    o.x          = j.value( "x", 0 );
    o.y          = j.value( "y", 0 );
    o.label_type = j.value( "label_type", "local" );
    o.rotation   = j.value( "rotation", 0.0 );
    return o;
}

inline nlohmann::json AddLabelOp::to_json() const {
    return { {"type","ADD_LABEL"}, {"name",name}, {"x",x}, {"y",y},
             {"label_type",label_type}, {"rotation",rotation} };
}

inline AddJunctionOp AddJunctionOp::from_json( const nlohmann::json& j ) {
    AddJunctionOp o;
    o.x = j.value( "x", 0 );
    o.y = j.value( "y", 0 );
    return o;
}

inline nlohmann::json AddJunctionOp::to_json() const {
    return { {"type","ADD_JUNCTION"}, {"x",x}, {"y",y} };
}

inline AddPowerSymbolOp AddPowerSymbolOp::from_json( const nlohmann::json& j ) {
    AddPowerSymbolOp o;
    o.net_name = j.value( "net_name", "" );
    o.x        = j.value( "x", 0 );
    o.y        = j.value( "y", 0 );
    o.rotation = j.value( "rotation", 0.0 );
    return o;
}

inline nlohmann::json AddPowerSymbolOp::to_json() const {
    return { {"type","ADD_POWER_SYMBOL"}, {"net_name",net_name},
             {"x",x}, {"y",y}, {"rotation",rotation} };
}

inline OperationVariant parseOperation( const nlohmann::json& j ) {
    const std::string t = j.value( "type", "" );
    const nlohmann::json& d = j.contains( "data" ) ? j["data"] : j;
    if( t == "PLACE_COMPONENT" )   return PlaceComponentOp::from_json( d );
    if( t == "ADD_WIRE" )          return AddWireOp::from_json( d );
    if( t == "ADD_LABEL" )         return AddLabelOp::from_json( d );
    if( t == "ADD_JUNCTION" )      return AddJunctionOp::from_json( d );
    if( t == "ADD_POWER_SYMBOL" )  return AddPowerSymbolOp::from_json( d );
    throw std::runtime_error( "unknown operation type: " + t );
}

inline ApplyPlan ApplyPlan::from_json( const nlohmann::json& j ) {
    ApplyPlan p;
    p.protocol_version = j.value( "protocol_version", PROTOCOL_VERSION );
    p.success          = j.value( "success", true );
    p.intent           = j.value( "intent", "generate" );
    p.message          = j.value( "message", "" );
    p.error            = j.value( "error", "" );
    if( j.contains( "operations" ) && j["operations"].is_array() ) {
        for( const auto& op : j["operations"] )
            p.operations.push_back( parseOperation( op ) );
    }
    if( j.contains( "plan" ) && j["plan"].is_object() ) {
        const auto& pj = j["plan"];
        p.plan.placement_info = pj.value( "placement_info", "" );
        if( pj.contains( "steps" ) && pj["steps"].is_array() ) {
            for( const auto& s : pj["steps"] ) {
                PlanStep st;
                st.index = s.value( "index", 0 );
                st.description = s.value( "description", "" );
                p.plan.steps.push_back( st );
            }
        }
    }
    if( j.contains( "erc" ) && j["erc"].is_object() ) {
        ErcReport er;
        er.errors   = j["erc"].value( "errors", 0 );
        er.warnings = j["erc"].value( "warnings", 0 );
        if( j["erc"].contains( "messages" ) && j["erc"]["messages"].is_array() ) {
            for( const auto& m : j["erc"]["messages"] ) {
                ErcMessage em;
                em.severity = m.value( "severity", "info" );
                em.code     = m.value( "code", "" );
                em.text     = m.value( "text", "" );
                if( m.contains( "refs" ) && m["refs"].is_array() )
                    for( const auto& r : m["refs"] )
                        em.refs.push_back( r.get<std::string>() );
                er.messages.push_back( em );
            }
        }
        p.erc = er;
    }
    return p;
}

} }  // namespace COPPER::generated
